-- Migration: Update allowed MIME types for the receipts storage bucket
-- Purpose: Allow WebP (generated by client-side compression), HEIC/HEIF (iPhone),
--          GIF, TIFF, BMP in addition to the existing JPEG, PNG, and PDF types.

UPDATE storage.buckets
SET allowed_mime_types = ARRAY[
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
  'image/heic',
  'image/heif',
  'image/tiff',
  'image/bmp',
  'application/pdf'
]
WHERE id = 'receipts';
